### PR TITLE
#3 Image/Object Segmentation Using Pixellib

### PR DESCRIPTION
**Pull request by Rahulraj31**
Image Object Segmentation files

### CODE REVIEW

**Comment by utkarshxy** [comment]
Change the name of the folder, please.

**Comment by Rahulraj31** [comment]
> Change the name of the folder, please.

To what? is ImageSegmentation fine??

**Comment by utkarshxy** [comment]
umm imageSegmentationUsingPixelLib ?

**Comment by Rahulraj31** [comment]
> umm imageSegmentationUsingPixelLib ?

ok

**Pull request closed without merging**
